# Generated by Django 3.2.6 on 2021-08-30 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='usuario_reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='categoria_reporte',
            field=models.CharField(choices=[('DANOS_EN_LA_VIA_PUBLICA', 'DAÑOS EN LA VIA PUBLICA'), ('DANOS_EN_ESPACIOS_PUBLICOS', 'DAÑOS EN ESPACIOS PÚBLICOS'), ('ANIMALES_ABANDONADOS_EN_LA_VIA_PUBLICA', 'ANIMALES ABANDONADOS EN LA VÍA PÚBLICA'), ('BASURA_EN_LUGARES_INCORRECTOS', 'BASURA EN LUGARES INCORRECTOS')], max_length=120),
        ),
    ]
