# Generated by Django 3.2.6 on 2021-09-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_usuario_reporte'),
        ('reportes', '0002_auto_20210830_1259'),
    ]

    operations = [
    ]
