# Generated by Django 3.2.6 on 2021-09-10 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_merge_20210909_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado_reporte',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='categoria_reporte',
            field=models.CharField(choices=[('DANOS_EN_LA_VIA_PUBLICA', 'Daños en la vía pública'), ('DANOS_EN_ESPACIOS_PUBLICOS', 'Daños en espacios públicos'), ('ANIMALES_ABANDONADOS_EN_LA_VIA_PUBLICA', 'Animales abandonados'), ('BASURA_EN_LUGARES_INCORRECTOS', 'Basura en lugares incorrectos')], max_length=120),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='sector_reporte',
            field=models.CharField(choices=[('SUR', 'Sur'), ('CENTRO', 'Centro'), ('NORTE', 'Norte')], max_length=40),
        ),
    ]
